upstream chat_web_base_manager {
    server chat-web-base-manager:8443;
    keepalive 16;
}

server {
    listen 80;
    listen [::]:80;
    server_name chat.lisfes.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name chat.lisfes.com;

    ssl_certificate /etc/nginx/certs/lisfes.pem;
    ssl_certificate_key /etc/nginx/certs/lisfes-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location / {
        proxy_pass https://chat_web_base_manager;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_ssl_name chat.lisfes.com;
        proxy_ssl_verify off;
        proxy_set_header Host chat.lisfes.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 10s;
        proxy_read_timeout 120s;
    }
}
